#!/bin/zsh

FIRST_CHARACTER="→"

prompt_short_pwd() {
  if [[ $PWD == $HOME ]]; then
    REPLY='~'
  else
    REPLY=${${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}/\/\//\/}
  fi
}

# Computed once per prompt, so PS1 expands variables and forks nothing.
prompt_precmd() {
  (( ${+functions[git-info]} )) && git-info
  prompt_short_pwd
  typeset -g _prompt_pwd=$REPLY _prompt_git=''
  [[ -n ${git_info} ]] && _prompt_git="%F{white} on ${(e)git_info[prompt]}"
}

prompt_setup() {
  local prompt_setup_status="%(?:%F{green}$FIRST_CHARACTER:%F{red}$FIRST_CHARACTER)%b"

  autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_precmd

  zstyle ':zim:git-info:branch' format '%F{green}%b'
  zstyle ':zim:git-info:commit' format '%c'
  zstyle ':zim:git-info:clean' format ' %F{white}'
  zstyle ':zim:git-info:dirty' format ' %F{yellow}'
  zstyle ':zim:git-info:keys' format 'prompt' '%F{cyan}%b%c%C%D'

  PS1='%F{yellow}${_prompt_pwd}${_prompt_git}%f
'"${prompt_setup_status} "
  export RPS1=''
}

prompt_setup "${@}"
