tap "buo/cask-upgrade"
tap "denisidoro/tools"
tap "homebrew/bundle"
tap "homebrew/services"

brew "sqlite"
brew "openssl"
brew "coreutils"
brew "nghttp2"
brew "fzf"
brew "gcc"
brew "git"
brew "htop" # https://hisham.hm/htop/
brew "jq"
brew "make"
brew "mysql"
brew "fnm"
brew "node"
brew "yarn"
brew "parallel" # https://www.gnu.org/software/parallel/
brew "shellcheck" # https://www.shellcheck.net/
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "tig" # https://jonas.github.io/tig
brew "bat"
brew "gpatch"
brew "pgcli"
brew "ripgrep"
brew "opam"
brew "fswatch"
brew "diff-so-fancy"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "httpie" # https://httpie.io
brew "hovrly"
brew "eza"

cask "firefox"
cask "figma"
cask "tableplus"
cask "google-drive"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoomus"
cask "notion"
cask "slack"
mas "The Unarchiver", id: 425424353
cask "discord"
cask "flux" # https://justgetflux.com/
cask "enpass" # https://www.enpass.io/
cask "kap" # https://getkap.co/
cask "rectangle" # https://rectangleapp.com/
cask "cloudflare-warp" # https://1.1.1.1/
cask "monitorcontrol" # https://github.com/MonitorControl/MonitorControl#readme
cask "alt-tab" # https://alt-tab-macos.netlify.app/
cask "insomnia" # https://insomnia.rest/
cask "raycast" # https://raycast.com/
cask "daisydisk" # https://daisydiskapp.com/
# Brave
# OBS
# Cursor
# Choosy
# Amphetamine
# DaisyDisk
# RDM
# noTunes
# camo studio
# xnapper

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
