tap "buo/cask-upgrade"
tap "jonahsnider/tap"

brew "sqlite"
brew "openssl"
brew "coreutils"
brew "nghttp2"
brew "fzf"
brew "gcc"
brew "git"
brew "htop" # https://hisham.hm/htop/
brew "jq"
brew "enpass-cli"
brew "make"
brew "mysql"
brew "fnm"
brew "parallel" # https://www.gnu.org/software/parallel/
brew "shellcheck" # https://www.shellcheck.net/
brew "shfmt" # Format and verify setup shell scripts
brew "gitleaks" # Scan setup files for credentials
brew "bats-core" # Run setup shell tests
brew "actionlint" # Validate setup workflows
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "tig" # https://jonas.github.io/tig
brew "bat"
brew "gpatch" # https://www.gnu.org/software/patch/
brew "pgcli"
brew "ripgrep"
brew "opam"
brew "fswatch"
brew "diff-so-fancy"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "httpie" # https://httpie.io
brew "eza"
brew "zoxide"
brew "gnupg"
brew "pkgconf"
brew "pinentry-mac"
brew "direnv"
brew "gh"
brew "opencode"
brew "hyperfine"
brew "mycli"

cask "firefox"
cask "google-chrome"
cask "hovrly"
cask "figma"
cask "tableplus"
cask "google-drive"
cask "spotify"
cask "telegram"
cask "jordanbaird-ice"
cask "wispr-flow"
cask "visual-studio-code"
cask "cursor"
cask "vlc"
cask "whatsapp"
cask "zoom"
cask "notion"
cask "slack"
mas "The Unarchiver", id: 425424353
mas "Amphetamine", id: 937984704
mas "Enpass", id: 732710998
cask "discord"
cask "flux-app" # https://justgetflux.com/
cask "kap" # https://getkap.co/
cask "rectangle" # https://rectangleapp.com/
cask "cloudflare-warp" # https://1.1.1.1/
cask "monitorcontrol" # https://github.com/MonitorControl/MonitorControl#readme
cask "alt-tab" # https://alt-tab-macos.netlify.app/
cask "insomnia" # https://insomnia.rest/
cask "raycast" # https://raycast.com/
cask "daisydisk" # https://daisydiskapp.com/
cask "brave-browser" # https://brave.com/
cask "obs" # https://obsproject.com/
cask "choosy" # https://www.choosyosx.com/
cask "betterdisplay" # https://betterdisplay.pro/
cask "noTunes" # https://apps.apple.com/app/no-tunes/id1544743990
cask "camo-studio" # https://apps.apple.com/app/camo-studio/id1544743990
cask "xnapper" # https://apps.apple.com/app/xnapper/id1544743990
cask "jonahsnider/tap/audio-priority-bar" # https://github.com/tobi/AudioPriorityBar

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
