unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind | split-window -h
bind - split-window -v

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind 0 select-window -t ':{start}'
bind 9 if-shell -F '#{e|>=:#{session_windows},9}' 'select-window -t :9' 'select-window -t ":$"'

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind x kill-pane
bind X run-shell 'if [ "#{session_windows}" -eq 1 ]; then /opt/homebrew/bin/tmux display-message "Cannot close the last window"; else /opt/homebrew/bin/tmux has-session -t __closed 2>/dev/null || /opt/homebrew/bin/tmux new-session -d -s __closed -n __placeholder; /opt/homebrew/bin/tmux move-window -a -s "#{window_id}" -t __closed:; /opt/homebrew/bin/tmux move-window -r -t "#{session_name}"; fi'
bind T run-shell 'if /opt/homebrew/bin/tmux list-windows -t __closed -F "##{window_name}" 2>/dev/null | /usr/bin/grep -qv "^__placeholder$"; then /opt/homebrew/bin/tmux move-window -a -s "__closed:{end}" -t "#{session_name}:"; /opt/homebrew/bin/tmux select-window -t "#{session_name}:{end}"; else /opt/homebrew/bin/tmux display-message "No closed window to restore"; fi'

set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g status-position top

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left ▌
set -g @nova-nerdfonts-right ▐

set -g @nova-pane-active-border-style "#44475a"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#161B23"
set -g @nova-status-style-fg "#d8dee9"
set -g @nova-status-style-active-bg "#89c0d0"
set -g @nova-status-style-active-fg "#2e3540"
set -g @nova-status-style-double-bg "#2d3540"

set -g @nova-pane "#I#{?pane_in_mode, #{pane_mode},} #W"

set -g @nova-segment-mode "#{?client_prefix,,}"
set -g @nova-segment-mode-colors "#78a2c1 #2e3440"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#78a2c1 #2e3440"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"

run-shell 'PATH=/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin ~/.tmux/plugins/tmux-nova/nova.tmux'

set -g status 2
set -g 'status-format[1]' ''
