confirm-close-surface = false
scrollback-limit = 4294967296

mouse-hide-while-typing = true
mouse-scroll-multiplier = 2

shell-integration = zsh
shell-integration-features = no-cursor,no-title,ssh-terminfo,ssh-env
command = /opt/homebrew/bin/tmux new-session -A -s main
title = Ghostty
window-decoration = true
window-inherit-working-directory = true
window-theme = ghostty
macos-titlebar-style = hidden

# Theme
window-padding-x = 10
window-padding-y = 20,10
window-padding-balance = false

font-size = 20
font-family = "JetBrains Mono"
font-thicken = false
font-feature = -liga
adjust-cell-height = 4
bold-is-bright = true

cursor-style = block
cursor-style-blink = true
unfocused-split-opacity = 0.9
background = #161B23
foreground = #C4B5B1

cursor-color = #E4B75E
cursor-text = #C4B5B1

selection-background = #434343
selection-foreground = #C4B5B1

split-divider-color = #36373C

# Normal colors (0-7)
palette = 0=#1A1A1A
palette = 1=#DB6165
palette = 2=#A6CC70
palette = 3=#FFA759
palette = 4=#D4BFFF
palette = 5=#C594C5
palette = 6=#68C1ED
palette = 7=#C4B5B1

# Bright colors (8-15)
palette = 8=#7F7F7F
palette = 9=#F28779
palette = 10=#BAE67E
palette = 11=#FFD580
palette = 12=#ACB9E9
palette = 13=#D4BFFF
palette = 14=#5CCFE6
palette = 15=#F6EFEF

# Keybinds

keybind = cmd+left=ignore
keybind = cmd+right=csi:F

# tmux windows (prefix: Ctrl-A)
keybind = cmd+n=text:\x01c
keybind = cmd+t=text:\x01c
keybind = cmd+shift+t=text:\x01T
keybind = cmd+tab=text:\x01n
keybind = cmd+shift+tab=text:\x01p
keybind = ctrl+tab=text:\x01n
keybind = ctrl+shift+tab=text:\x01p
keybind = cmd+digit_1=text:\x01\x31
keybind = cmd+1=text:\x01\x31
keybind = cmd+digit_2=text:\x01\x32
keybind = cmd+2=text:\x01\x32
keybind = cmd+digit_3=text:\x01\x33
keybind = cmd+3=text:\x01\x33
keybind = cmd+digit_4=text:\x01\x34
keybind = cmd+4=text:\x01\x34
keybind = cmd+digit_5=text:\x01\x35
keybind = cmd+5=text:\x01\x35
keybind = cmd+digit_6=text:\x01\x36
keybind = cmd+6=text:\x01\x36
keybind = cmd+digit_7=text:\x01\x37
keybind = cmd+7=text:\x01\x37
keybind = cmd+digit_8=text:\x01\x38
keybind = cmd+8=text:\x01\x38
keybind = cmd+9=text:\x01\x39
keybind = cmd+0=text:\x01\x30

# tmux panes
keybind = cmd+w=text:\x01x
keybind = cmd+shift+w=text:\x01X
keybind = cmd+d=text:\x01|
keybind = cmd+shift+d=text:\x01-
keybind = opt+shift+left=text:\x01h
keybind = opt+shift+right=text:\x01l
keybind = opt+shift+up=text:\x01k
keybind = opt+shift+down=text:\x01j

# Classic MacOS in spanish ._.
keybind = opt+ñ=text:~
keybind = cmd+shift+r=reload_config
keybind = shift+enter=text:\n
keybind = control+enter=text:\n
